Repository function-future/function-backend, pull requests merged in 2020-01, with the labels that each got.

#300 Bugfix/SCORING-6 return trials left
  function-web/src/main/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapper.java
  function-web/src/test/java/com/future/function/web/controller/scoring/StudentQuestionControllerTest.java
  function-web/src/test/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapperTest.java
Labels: bug

#303 Scoring 7 create time limit endpoint
  function-service-api/src/main/java/com/future/function/service/api/feature/scoring/StudentQuizService.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/scoring/StudentQuizServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/scoring/StudentQuizServiceImplTest.java
  function-web/src/main/java/com/future/function/web/controller/scoring/StudentQuestionController.java
  function-web/src/main/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapper.java
  function-web/src/test/java/com/future/function/web/controller/scoring/StudentQuestionControllerTest.java
  function-web/src/test/java/com/future/function/web/mapper/response/scoring/StudentQuizDetailResponseMapperTest.java
Labels: enhancement

#318 [feature/CI] Setup CI and Sonarcloud Analysis
  .github/workflows/install_and_sonarcloud.yml
  pom.xml
Labels: enhancement

#321 [bugfix/CORE-75] Delete students and shared courses when batch is deleted
  function-repository/pom.xml
  function-repository/src/main/java/com/future/function/repository/listener/core/BatchMongoEventListener.java
  function-repository/src/test/java/com/future/function/repository/listener/core/BatchMongoEventListenerTest.java
  function-service-api/src/main/java/com/future/function/service/api/feature/core/ResourceService.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/ResourceServiceImpl.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ResourceServiceImplTest.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java
  pom.xml
Labels: bug

#310 [bugfix/CORE-84] NPE on FileMustBeImageValidator if file is not found on repository
  function-validation/src/main/java/com/future/function/validation/validator/core/FileMustBeImageValidator.java
  function-validation/src/test/java/com/future/function/validation/validator/core/FileMustBeImageValidatorTest.java
Labels: bug

#314 [bugfix/CORE-85] Check validation of userId on getting activity blogs by specific user id
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/ActivityBlogServiceImplTest.java
Labels: bug

#322 [bugfix/CORE-76] Prevent admin to delete himself while logged in
  function-web/src/main/java/com/future/function/web/controller/core/UserController.java
  function-web/src/main/java/com/future/function/web/mapper/request/core/UserRequestMapper.java
  function-web/src/test/java/com/future/function/web/controller/core/UserControllerTest.java
  function-web/src/test/java/com/future/function/web/mapper/request/core/UserRequestMapperTest.java
Labels: bug

#320 Change run command and rename actions file
  .github/workflows/install_and_sonarcloud.yml
  .github/workflows/sonarcloud.yml
  pom.xml
Labels: bug

#298 Updated menuList for scoring-related pages
  function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_020.java
Labels: enhancement, help wanted

#335 [bugfix/CORE-88] Incorrect result from validateNotLoggedInUser
  function-web/src/main/java/com/future/function/web/mapper/request/core/UserRequestMapper.java
  function-web/src/test/java/com/future/function/web/mapper/request/core/UserRequestMapperTest.java
Labels: bug

#339 [bugfix/CORE-90] NPE on creating course file copy
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java
Labels: bug

#343 [bugfix/CORE-91] Prevent non-batch student from accessing other batches' shared courses data
  function-service-api/src/main/java/com/future/function/service/api/feature/core/SharedCourseService.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/SharedCourseServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/SharedCourseServiceImplTest.java
  function-web/src/main/java/com/future/function/web/controller/core/SharedCourseController.java
  function-web/src/test/java/com/future/function/web/controller/core/SharedCourseControllerTest.java
Labels: bug

#354 [feature/CORE-94] Change get batches return type to List
  docs/API/core/batches-api.md
  function-repository/src/main/java/com/future/function/repository/feature/core/BatchRepository.java
  function-repository/src/test/java/com/future/function/repository/feature/core/BatchRepositoryTest.java
  function-service-api/src/main/java/com/future/function/service/api/feature/core/BatchService.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/BatchServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/BatchServiceImplTest.java
  function-web/src/main/java/com/future/function/web/controller/core/BatchController.java
  function-web/src/main/java/com/future/function/web/mapper/response/core/BatchResponseMapper.java
  function-web/src/test/java/com/future/function/web/controller/core/BatchControllerTest.java
  function-web/src/test/java/com/future/function/web/mapper/response/core/BatchResponseMapperTest.java
Labels: enhancement

#360 [feature/CORE-96] Refactor file/folder path database storage implementation
  function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_002.java
  function-data-migration/src/main/java/com/future/function/data/migration/change/log/DataMigration_025.java
  function-model/src/main/java/com/future/function/model/entity/feature/core/FileV2.java
  function-model/src/main/java/com/future/function/model/entity/feature/core/embedded/FilePath.java
  function-service-api/src/main/java/com/future/function/service/api/feature/core/FileService.java
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/FileServiceImpl.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/FileServiceImplTest.java
  function-web/src/main/java/com/future/function/web/mapper/response/core/FileResponseMapper.java
  function-web/src/test/java/com/future/function/web/controller/core/FileControllerTest.java
  function-web/src/test/java/com/future/function/web/mapper/response/core/FileResponseMapperTest.java
Labels: enhancement

#362 [bugfix/CORE-97] Incorrect email password
  function-app/src/main/resources/application-local.properties
  function-app/src/main/resources/application-no-mock.properties
Labels: bug

#358 [bugfix/CORE-95] FileDeleteScheduler not deleting file versions
  function-service-impl/src/main/java/com/future/function/service/impl/feature/core/scheduler/FileDeleteScheduler.java
  function-service-impl/src/test/java/com/future/function/service/impl/feature/core/scheduler/FileDeleteSchedulerTest.java
Labels: bug
